from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent
REGISTRY_REL_PATH = "data/evaluation/shared/source_registry.json"


@dataclass(frozen=True)
class SourceDocument:
    source_id: str
    title: str
    doc_type: str
    category: str
    language: str
    raw_relpath: str
    clean_relpath: str
    origin_url: str
    version: str
    topic_tags: tuple[str, ...]
    summary_hint: str

    @property
    def raw_path(self) -> Path:
        return ROOT / self.raw_relpath

    @property
    def clean_path(self) -> Path:
        return ROOT / self.clean_relpath


SOURCE_DOCUMENTS: tuple[SourceDocument, ...] = (
    SourceDocument(
        source_id="apollo-doc-001",
        title="Apollo Developer Center Learning Path",
        doc_type="official_doc",
        category="apollo",
        language="en",
        raw_relpath="data/sources/raw/apollo/apollo-devcenter-learning-path.pdf",
        clean_relpath="data/sources/apollo/apollo-devcenter-learning-path.md",
        origin_url="https://developer.apollo.auto/devcenter/devcenter.html",
        version="Apollo Developer Center",
        topic_tags=("system_architecture", "perception", "planning_control"),
        summary_hint="Official Apollo learning-path material that explains the major modules, their order of study, and how perception, prediction, planning, control, and localization fit together.",
    ),
    SourceDocument(
        source_id="apollo-doc-002",
        title="Apollo Cyber RT Framework",
        doc_type="official_doc",
        category="apollo",
        language="en",
        raw_relpath="data/sources/raw/apollo/Apollo-Cyber-RT-framework.pdf",
        clean_relpath="data/sources/apollo/apollo-cyber-rt.md",
        origin_url="https://developer.apollo.auto/cyber.html",
        version="Apollo Cyber RT",
        topic_tags=("system_architecture", "planning_control"),
        summary_hint="Official Apollo runtime-framework material describing Cyber RT, its component model, scheduling model, and how it supports low-latency autonomous-driving workloads.",
    ),
    SourceDocument(
        source_id="apollo-doc-003",
        title="Apollo Channel Data Format",
        doc_type="official_doc",
        category="apollo",
        language="zh",
        raw_relpath="data/sources/raw/apollo/apollo-channel-data-format.pdf",
        clean_relpath="data/sources/apollo/apollo-channel-data-format.md",
        origin_url="https://developer.apollo.auto/Apollo-Homepage-Document/Apollo_Doc_CN_6_0/%E6%95%B0%E6%8D%AE%E6%A0%BC%E5%BC%8F/Channel%E6%95%B0%E6%8D%AE%E6%A0%BC%E5%BC%8F%E6%96%87%E6%A1%A3%E4%BB%8B%E7%BB%8D",
        version="Apollo Doc CN 6.0",
        topic_tags=("system_architecture", "sensor_fusion", "planning_control"),
        summary_hint="Official Apollo channel-format material describing how modules communicate through Cyber RT channels and which message types are used for perception, prediction, planning, and control.",
    ),
    SourceDocument(
        source_id="apollo-doc-004",
        title="Apollo Open Platform Overview",
        doc_type="official_doc",
        category="apollo",
        language="en",
        raw_relpath="data/sources/raw/apollo/Apollo-Open-Platform-overview.pdf",
        clean_relpath="data/sources/apollo/apollo-open-platform-overview.md",
        origin_url="https://developer.apollo.auto/developer.html",
        version="Apollo Open Platform",
        topic_tags=("system_architecture", "perception", "planning_control"),
        summary_hint="Official platform-overview material describing Apollo’s software stack, hardware stack, and module boundaries across perception, localization, planning, control, and simulation.",
    ),
    SourceDocument(
        source_id="apollo-doc-005",
        title="Apollo Perception Fusion Overview",
        doc_type="official_doc",
        category="apollo",
        language="zh",
        raw_relpath="data/sources/raw/apollo/apollo-perception-fusion-overview.pdf",
        clean_relpath="data/sources/apollo/apollo-perception-fusion-overview.md",
        origin_url="https://developer.apollo.auto/Apollo-Homepage-Document/Apollo_Doc_CN_6_0/%E4%B8%8A%E6%9C%BA%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B/%E4%B8%8A%E6%9C%BA%E5%AE%9E%E8%B7%B5Apollo%E6%84%9F%E7%9F%A5%E8%9E%8D%E5%90%88%E8%83%BD%E5%8A%9B/Apollo%E6%84%9F%E7%9F%A5%E8%9E%8D%E5%90%88%E8%83%BD%E5%8A%9B%E4%BB%8B%E7%BB%8D",
        version="Apollo Doc CN 6.0",
        topic_tags=("perception", "sensor_fusion"),
        summary_hint="Official Apollo perception-fusion material describing the multi-sensor fusion workflow and the role of fused perception in downstream driving tasks.",
    ),
    SourceDocument(
        source_id="apollo-doc-006",
        title="Apollo Vision Perception Overview",
        doc_type="official_doc",
        category="apollo",
        language="zh",
        raw_relpath="data/sources/raw/apollo/apollo-vision-perception-overview.pdf",
        clean_relpath="data/sources/apollo/apollo-vision-perception-overview.md",
        origin_url="https://developer.apollo.auto/platform/perception_cn.html",
        version="Apollo Perception CN",
        topic_tags=("perception", "sensor_fusion"),
        summary_hint="Official Apollo perception material describing the perception module, its obstacle understanding responsibilities, and how visual perception supports autonomous driving.",
    ),
    SourceDocument(
        source_id="apollo-doc-007",
        title="Apollo Prediction Overview",
        doc_type="official_doc",
        category="apollo",
        language="zh",
        raw_relpath="data/sources/raw/apollo/apollo-vision-prediction-overview.pdf",
        clean_relpath="data/sources/apollo/apollo-vision-prediction-overview.md",
        origin_url="https://developer.apollo.auto/Apollo-Homepage-Document/Apollo_Doc_CN_6_0/%E4%B8%8A%E6%9C%BA%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B/%E4%B8%8A%E6%9C%BA%E5%AE%9E%E8%B7%B5Apollo%E9%A2%84%E6%B5%8B%E8%83%BD%E5%8A%9B/Apollo%E9%A2%84%E6%B5%8B%E8%83%BD%E5%8A%9B%E4%BB%8B%E7%BB%8D",
        version="Apollo Doc CN 6.0",
        topic_tags=("planning_control", "perception"),
        summary_hint="Official Apollo prediction material describing how the system predicts surrounding-agent behavior and feeds that forecast into planning.",
    ),
    SourceDocument(
        source_id="apollo-doc-008",
        title="Apollo Planning Overview",
        doc_type="official_doc",
        category="apollo",
        language="zh",
        raw_relpath="data/sources/raw/apollo/apollo-vision-plan-overview.pdf",
        clean_relpath="data/sources/apollo/apollo-vision-plan-overview.md",
        origin_url="https://developer.apollo.auto/Apollo-Homepage-Document/Apollo_Doc_CN_6_0/%E4%B8%8A%E6%9C%BA%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B/%E4%B8%8A%E6%9C%BA%E5%AE%9E%E8%B7%B5Apollo%E8%A7%84%E5%88%92%E8%83%BD%E5%8A%9B/apollo%E8%A7%84%E5%88%92%E8%83%BD%E5%8A%9B%E4%BB%8B%E7%BB%8D",
        version="Apollo Doc CN 6.0",
        topic_tags=("planning_control", "system_architecture"),
        summary_hint="Official Apollo planning material describing scenario-based planning, planner responsibilities, and the inputs and outputs of the planning module.",
    ),
    SourceDocument(
        source_id="apollo-doc-009",
        title="Apollo Control Overview",
        doc_type="official_doc",
        category="apollo",
        language="zh",
        raw_relpath="data/sources/raw/apollo/apollo-vision-control-overview.pdf",
        clean_relpath="data/sources/apollo/apollo-vision-control-overview.md",
        origin_url="https://developer.apollo.auto/Apollo-Homepage-Document/Apollo_Doc_CN_6_0/%E4%B8%8A%E6%9C%BA%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B/%E4%B8%8A%E6%9C%BA%E5%AE%9E%E8%B7%B5Apollo%E6%8E%A7%E5%88%B6%E8%83%BD%E5%8A%9B/Apollo%20%E6%8E%A7%E5%88%B6%E8%83%BD%E5%8A%9B%E4%BB%8B%E7%BB%8D",
        version="Apollo Doc CN 6.0",
        topic_tags=("planning_control", "system_architecture"),
        summary_hint="Official Apollo control material describing how planned trajectories are converted into steering, throttle, and brake commands.",
    ),
    SourceDocument(
        source_id="apollo-doc-010",
        title="Apollo Localization Overview",
        doc_type="official_doc",
        category="apollo",
        language="zh",
        raw_relpath="data/sources/raw/apollo/apollo-vision-location-overview.pdf",
        clean_relpath="data/sources/apollo/apollo-vision-location-overview.md",
        origin_url="https://developer.apollo.auto/Apollo-Homepage-Document/Apollo_Doc_CN_6_0/%E4%B8%8A%E6%9C%BA%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B/%E4%B8%8A%E6%9C%BA%E5%AE%9E%E8%B7%B5Apollo%E5%AE%9A%E4%BD%8D%E8%83%BD%E5%8A%9B/Apollo%E5%AE%9A%E4%BD%8D%E8%83%BD%E5%8A%9B%E4%BB%8B%E7%BB%8D/",
        version="Apollo Doc CN 6.0",
        topic_tags=("system_architecture", "planning_control"),
        summary_hint="Official Apollo localization material describing the localization stack, map alignment, and the role of high-precision position estimation in autonomous driving.",
    ),
    SourceDocument(
        source_id="standard-001",
        title="NHTSA Automated Driving Systems Overview",
        doc_type="standard",
        category="standards",
        language="en",
        raw_relpath="data/sources/raw/standards/NHTSA ADS overview.pdf",
        clean_relpath="data/sources/standards/nhtsa-ads-overview.md",
        origin_url="https://www.nhtsa.gov/automated-vehicles/vision-safety",
        version="NHTSA ADS Overview",
        topic_tags=("safety", "system_architecture"),
        summary_hint="Official NHTSA overview material describing automated driving systems from the U.S. safety-regulation perspective.",
    ),
    SourceDocument(
        source_id="standard-002",
        title="Automated Driving Systems 2.0: A Vision for Safety",
        doc_type="standard",
        category="standards",
        language="en",
        raw_relpath="data/sources/raw/standards/Automated Driving Systems 2.0 A Vision for Safety.pdf",
        clean_relpath="data/sources/standards/ads-2-0-vision-for-safety.md",
        origin_url="https://www.nhtsa.gov/sites/nhtsa.gov/files/documents/13069a-ads2.0_090617_v9a_tag.pdf",
        version="ADS 2.0",
        topic_tags=("safety", "system_architecture"),
        summary_hint="Official NHTSA voluntary-guidance document describing high-level safety expectations for automated driving systems.",
    ),
    SourceDocument(
        source_id="standard-003",
        title="Preparing for the Future of Transportation: Automated Vehicles 3.0",
        doc_type="standard",
        category="standards",
        language="en",
        raw_relpath="data/sources/raw/standards/Preparing for the Future of Transportation Automated Vehicles 3.0.pdf",
        clean_relpath="data/sources/standards/av-3-0-preparing-for-the-future-of-transportation.md",
        origin_url="https://www.transportation.gov/sites/dot.gov/files/docs/policy-initiatives/automated-vehicles/320711/preparing-future-transportation-automated-vehicle-30.pdf",
        version="AV 3.0",
        topic_tags=("safety", "system_architecture"),
        summary_hint="Official U.S. DOT automated-vehicle policy document describing broader transportation and regulatory context around automated vehicles.",
    ),
    SourceDocument(
        source_id="standard-004",
        title="Ensuring American Leadership in Automated Vehicle Technologies: AV 4.0",
        doc_type="standard",
        category="standards",
        language="en",
        raw_relpath="data/sources/raw/standards/Ensuring American Leadership in Automated Vehicle Technologies AV 4.0.pdf",
        clean_relpath="data/sources/standards/av-4-0-ensuring-american-leadership.md",
        origin_url="https://www.transportation.gov/sites/dot.gov/files/docs/policy-initiatives/automated-vehicles/360956/ensuringamericanleadershipav4.pdf",
        version="AV 4.0",
        topic_tags=("safety", "system_architecture"),
        summary_hint="Official U.S. DOT automated-vehicle strategy document describing federal automated-vehicle priorities and cross-agency coordination.",
    ),
    SourceDocument(
        source_id="standard-005",
        title="Automated Driving System Safety: Overview of NHTSA Activities",
        doc_type="standard",
        category="standards",
        language="en",
        raw_relpath="data/sources/raw/standards/Automated Driving System Safety Overview of NHTSA Activities.pdf",
        clean_relpath="data/sources/standards/nhtsa-ads-safety-overview.md",
        origin_url="https://www.nhtsa.gov/document/automated-driving-system-safety-overview-nhtsa-activities-0",
        version="NHTSA Activities Overview",
        topic_tags=("safety",),
        summary_hint="Official NHTSA material summarizing the agency’s activities and safety priorities for automated driving systems.",
    ),
    SourceDocument(
        source_id="standard-006",
        title="Overview of Select NHTSA Activities – Automated Driving Systems",
        doc_type="standard",
        category="standards",
        language="en",
        raw_relpath="data/sources/raw/standards/Overview of Select NHTSA Activities – Automated Driving Systems.pdf",
        clean_relpath="data/sources/standards/nhtsa-select-ads-activities-overview.md",
        origin_url="https://www.nhtsa.gov/sites/nhtsa.gov/files/2024-02/16180-NSR-231211-007_SAE_Overview%20of%20Select%20NHTSA%20Activities%20-%20Automated%20Driving%20Systems-tag.pdf",
        version="NHTSA Select Activities Overview",
        topic_tags=("safety",),
        summary_hint="Official NHTSA material highlighting selected automated-driving-system activities and the agency’s current program emphasis.",
    ),
    SourceDocument(
        source_id="standard-007",
        title="UN Regulation No. 155 - Cyber security and cyber security management system",
        doc_type="standard",
        category="standards",
        language="en",
        raw_relpath="data/sources/raw/standards/UN Regulation No. 155 - Cyber security and cyber security management system.pdf",
        clean_relpath="data/sources/standards/unece-r155-cyber-security-management-system.md",
        origin_url="https://unece.org/sites/default/files/2023-02/R155e%20%282%29.pdf",
        version="UN R155",
        topic_tags=("safety",),
        summary_hint="Official UNECE regulation text covering vehicle cyber-security requirements and the cyber-security management system.",
    ),
    SourceDocument(
        source_id="standard-008",
        title="UN Regulation No. 156 - Software update and software update management system",
        doc_type="standard",
        category="standards",
        language="en",
        raw_relpath="data/sources/raw/standards/UN Regulation No. 156 - Software update and software update management system.pdf",
        clean_relpath="data/sources/standards/unece-r156-software-update-management-system.md",
        origin_url="https://unece.org/sites/default/files/2024-03/R156e%20%282%29.pdf",
        version="UN R156",
        topic_tags=("safety",),
        summary_hint="Official UNECE regulation text covering software update requirements and the software update management system.",
    ),
    SourceDocument(
        source_id="standard-009",
        title="UN Regulation No. 157 - Automated Lane Keeping Systems (ALKS)",
        doc_type="standard",
        category="standards",
        language="en",
        raw_relpath="data/sources/raw/standards/UN Regulation No. 157 - Automated Lane Keeping Systems (ALKS).pdf",
        clean_relpath="data/sources/standards/unece-r157-alks.md",
        origin_url="https://unece.org/sites/default/files/2025-06/R157r1e.pdf",
        version="UN R157",
        topic_tags=("safety", "planning_control"),
        summary_hint="Official UNECE regulation text covering automated lane keeping systems and the operating conditions for that automated-driving function.",
    ),
    SourceDocument(
        source_id="paper-001",
        title="BEVFormer",
        doc_type="paper",
        category="papers",
        language="en",
        raw_relpath="data/sources/raw/papers/BEVFormer.pdf",
        clean_relpath="data/sources/papers/bevformer.md",
        origin_url="unknown",
        version="BEVFormer",
        topic_tags=("perception", "sensor_fusion"),
        summary_hint="Research paper on bird’s-eye-view perception that uses spatiotemporal transformers to build BEV features for autonomous-driving perception tasks.",
    ),
    SourceDocument(
        source_id="paper-002",
        title="BEVFusion",
        doc_type="paper",
        category="papers",
        language="en",
        raw_relpath="data/sources/raw/papers/BEVFusion.pdf",
        clean_relpath="data/sources/papers/bevfusion.md",
        origin_url="unknown",
        version="BEVFusion",
        topic_tags=("perception", "sensor_fusion"),
        summary_hint="Research paper on unified BEV fusion across LiDAR and camera inputs for robust autonomous-driving perception.",
    ),
    SourceDocument(
        source_id="paper-003",
        title="Occupancy Flow Fields for Motion Forecasting in Autonomous Driving",
        doc_type="paper",
        category="papers",
        language="en",
        raw_relpath="data/sources/raw/papers/Occupancy Flow Fields for Motion Forecasting in Autonomous Driving.pdf",
        clean_relpath="data/sources/papers/occupancy-flow-fields.md",
        origin_url="unknown",
        version="Occupancy Flow Fields",
        topic_tags=("planning_control", "perception"),
        summary_hint="Research paper on occupancy-based motion forecasting for autonomous driving, connecting scene understanding to downstream behavior prediction.",
    ),
    SourceDocument(
        source_id="paper-004",
        title="Scalability in Perception for Autonomous Driving: Waymo Open Dataset",
        doc_type="report",
        category="papers",
        language="en",
        raw_relpath="data/sources/raw/papers/Scalability in Perception for Autonomous Driving Waymo Open Dataset.pdf",
        clean_relpath="data/sources/papers/waymo-scalability-perception.md",
        origin_url="unknown",
        version="Waymo Open Dataset Report",
        topic_tags=("perception", "system_architecture"),
        summary_hint="Technical report from the Waymo Open Dataset context explaining perception scalability and dataset-driven evaluation considerations for autonomous driving.",
    ),
    SourceDocument(
        source_id="paper-005",
        title="VAD: Vectorized Scene Representation for Efficient Autonomous Driving",
        doc_type="paper",
        category="papers",
        language="en",
        raw_relpath="data/sources/raw/papers/VAD Vectorized Scene Representation for Efficient Autonomous Driving.pdf",
        clean_relpath="data/sources/papers/vad.md",
        origin_url="https://arxiv.org/abs/2303.12077",
        version="VAD",
        topic_tags=("planning_control", "perception"),
        summary_hint="End-to-end autonomous-driving research paper using vectorized scene representation to connect perception, prediction, and planning efficiently.",
    ),
    SourceDocument(
        source_id="paper-006",
        title="FusionAD: Multi-modality Fusion for Prediction and Planning Tasks of Autonomous Driving",
        doc_type="paper",
        category="papers",
        language="en",
        raw_relpath="data/sources/raw/papers/FusionAD Multi-modality Fusion for Prediction and Planning Tasks of Autonomous.pdf",
        clean_relpath="data/sources/papers/fusionad.md",
        origin_url="https://arxiv.org/abs/2308.01006",
        version="FusionAD",
        topic_tags=("planning_control", "sensor_fusion"),
        summary_hint="Research paper on multimodal fusion for prediction and planning, targeted at end-to-end autonomous-driving behavior generation.",
    ),
    SourceDocument(
        source_id="paper-007",
        title="GenAD: Generative End-to-End Autonomous Driving",
        doc_type="paper",
        category="papers",
        language="en",
        raw_relpath="data/sources/raw/papers/GenAD Generative End-to-End Autonomous Driving.pdf",
        clean_relpath="data/sources/papers/genad.md",
        origin_url="https://arxiv.org/abs/2402.11502",
        version="GenAD",
        topic_tags=("planning_control", "perception"),
        summary_hint="Generative end-to-end autonomous-driving research paper that models motion prediction and planning as a unified generation problem.",
    ),
)


def all_documents() -> tuple[SourceDocument, ...]:
    return SOURCE_DOCUMENTS


def documents_for_category(category: str) -> tuple[SourceDocument, ...]:
    return tuple(doc for doc in SOURCE_DOCUMENTS if doc.category == category)
