/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifact */
        get: operations["get_artifact_artifacts__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Asset */
        post: operations["upload_asset_assets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Asset */
        get: operations["get_asset_assets__asset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assistant/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Assistant Message
         * @description Persist the first assistant message and room in one repository boundary.
         */
        post: operations["assistant_message_assistant_messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/commands/{command_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute Command */
        post: operations["execute_command_commands__command_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/persona-bindings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bind Persona */
        post: operations["bind_persona_persona_bindings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/persona-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save Persona */
        post: operations["save_persona_persona_profiles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/persona-profiles/{persona_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Persona */
        get: operations["get_persona_persona_profiles__persona_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/compile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compile Plan */
        post: operations["compile_plan_plans_compile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Roles */
        get: operations["list_roles_roles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rooms */
        get: operations["list_rooms_rooms_get"];
        put?: never;
        /** Create Room */
        post: operations["create_room_rooms_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{room_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Room */
        get: operations["get_room_rooms__room_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{room_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_rooms__room_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{room_id}/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Events */
        get: operations["stream_events_rooms__room_id__events_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{room_id}/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Event */
        get: operations["get_event_rooms__room_id__events__event_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{room_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Members */
        get: operations["list_members_rooms__room_id__members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{room_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Messages */
        get: operations["list_messages_rooms__room_id__messages_get"];
        put?: never;
        /** Create Message */
        post: operations["create_message_rooms__room_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{room_id}/multi-agent/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute Multi Agent */
        post: operations["execute_multi_agent_rooms__room_id__multi_agent_execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Run */
        post: operations["create_run_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model Settings */
        get: operations["model_settings_settings_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/models/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Model Setting */
        put: operations["update_model_setting_settings_models__agent_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Task */
        post: operations["create_task_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}/followups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Followup */
        post: operations["create_followup_tasks__task_id__followups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Task Message */
        post: operations["create_task_message_tasks__task_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssetUploadRequest */
        AssetUploadRequest: {
            /** Content Base64 */
            content_base64: string;
            /**
             * Evaluate
             * @default false
             */
            evaluate: boolean;
            /** Filename */
            filename: string;
            /**
             * Space Id
             * @default default
             */
            space_id: string;
        };
        /** AssetUploadResponse */
        AssetUploadResponse: {
            /** Asset Id */
            asset_id: string;
            /** Chunks */
            chunks: string[];
            /** Content Hash */
            content_hash: string;
            /** Evaluation Requested */
            evaluation_requested: boolean;
            /**
             * Evaluation Status
             * @enum {string}
             */
            evaluation_status: "not_requested" | "requested";
            /** Media Type */
            media_type: string;
            /** Object Path */
            object_path: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** AssistantMessageRequest */
        AssistantMessageRequest: {
            /** Content */
            content: string;
            /** Room Id */
            room_id?: string | null;
            /** Space Id */
            space_id: string;
            /**
             * Title
             * @default
             */
            title: string;
        };
        /** AssistantMessageResponse */
        AssistantMessageResponse: {
            /** Created */
            created: boolean;
            message: components["schemas"]["MessageResponse"];
            room: components["schemas"]["RoomResponse"];
        };
        /** CommandRequest */
        CommandRequest: {
            /**
             * Action
             * @enum {string}
             */
            action: "start" | "pause" | "cancel";
            /** Expected Control Epoch */
            expected_control_epoch?: number | null;
            /** Expected Row Version */
            expected_row_version: number;
            /** Run Id */
            run_id: string;
        };
        /** CommandResponse */
        CommandResponse: {
            /** Command Id */
            command_id: string;
            run: components["schemas"]["RunResponse"];
            /**
             * Status
             * @constant
             */
            status: "accepted";
        };
        /** EventIdentityResponse */
        EventIdentityResponse: {
            /** Event Id */
            event_id: string;
            /** Room Id */
            room_id: string;
            /** Room Sequence */
            room_sequence: number;
        };
        /** EventListResponse */
        EventListResponse: {
            /** Items */
            items: components["schemas"]["EventResponse"][];
            /** Next */
            next: number;
        };
        /** EventResponse */
        EventResponse: {
            /** Attempt Id */
            attempt_id: string | null;
            /** Caused By */
            caused_by: string[];
            /** Consumes */
            consumes: string[];
            /** Event Type */
            event_type: string;
            identity: components["schemas"]["EventIdentityResponse"];
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Produces */
            produces: string[];
            /** Room Id */
            room_id: string;
            /** Run Id */
            run_id: string | null;
            /** Run Sequence */
            run_sequence: number;
            /** Step Id */
            step_id: string | null;
            /** Task Id */
            task_id: string | null;
            /** Timestamp */
            timestamp: string;
            /** Usage */
            usage: {
                [key: string]: number;
            };
        };
        /** FollowupRequest */
        FollowupRequest: {
            /** Content */
            content: string;
            /** Expected Task Version */
            expected_task_version?: number | null;
        };
        /** FollowupResponse */
        FollowupResponse: {
            message: components["schemas"]["MessageResponse"];
            /** Run Id */
            run_id: string | null;
            /**
             * Status
             * @constant
             */
            status: "accepted";
            task: components["schemas"]["TaskResponse"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Contract */
            contract: string;
            /** Status */
            status: string;
        };
        /** MemberListResponse */
        MemberListResponse: {
            /** Items */
            items: components["schemas"]["MemberResponse"][];
        };
        /** MemberResponse */
        MemberResponse: {
            /** Agent Id */
            agent_id: string;
            /** Joined At */
            joined_at: string | null;
            /** Left At */
            left_at: string | null;
            /** Membership Id */
            membership_id: string;
            /** Room Id */
            room_id: string;
            /** Status */
            status: string;
        };
        /** MessageCreateRequest */
        MessageCreateRequest: {
            /** Content */
            content: string;
            /** Message Id */
            message_id?: string | null;
            /**
             * Role
             * @default user
             * @enum {string}
             */
            role: "user" | "assistant" | "system" | "tool";
        };
        /** MessageListResponse */
        MessageListResponse: {
            /** Items */
            items: components["schemas"]["MessageResponse"][];
            /**
             * Next
             * @default 0
             */
            next: number;
        };
        /** MessageResponse */
        MessageResponse: {
            /** Content */
            content: string;
            /** Content Sha256 */
            content_sha256: string;
            /** Created At */
            created_at: string | null;
            /** Idempotency Key */
            idempotency_key: string | null;
            /** Message Id */
            message_id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant" | "system" | "tool";
            /** Room Id */
            room_id: string;
            /** Room Sequence */
            room_sequence: number;
            /** Status */
            status: string;
        };
        /** ModelAgentSetting */
        ModelAgentSetting: {
            /** Agent Id */
            agent_id: string;
            /** Capabilities */
            capabilities: string[];
            /** Display Name */
            display_name: string;
            /** Max Concurrency */
            max_concurrency: number;
            /** Modalities */
            modalities: string[];
            /** Model */
            model: string;
            /** Model Profile */
            model_profile: string;
            /** Provider */
            provider: string;
            /** Responsibility */
            responsibility: string;
            /** Tier */
            tier: string;
        };
        /** ModelBindingUpdateRequest */
        ModelBindingUpdateRequest: {
            /** Source Agent Id */
            source_agent_id: string;
            /** Tier */
            tier?: string | null;
        };
        /** ModelChoice */
        ModelChoice: {
            /** Base Url */
            base_url: string;
            /** Capabilities */
            capabilities: string[];
            /** Max Concurrency */
            max_concurrency: number;
            /** Modalities */
            modalities: string[];
            /** Model */
            model: string;
            /** Model Profile */
            model_profile: string;
            /** Provider */
            provider: string;
            /** Source Agent Id */
            source_agent_id: string;
        };
        /** ModelSettingsResponse */
        ModelSettingsResponse: {
            /** Agents */
            agents: components["schemas"]["ModelAgentSetting"][];
            /** Models */
            models: components["schemas"]["ModelChoice"][];
        };
        /** MultiAgentExecuteRequest */
        MultiAgentExecuteRequest: {
            /**
             * Architecture
             * @default auto
             * @enum {string}
             */
            architecture: "auto" | "direct" | "hierarchical" | "swarm" | "adversarial" | "heterogeneous" | "graph";
            /**
             * Background
             * @default false
             */
            background: boolean;
            /** Goal */
            goal: string;
            /**
             * Max Agents
             * @default 3
             */
            max_agents: number;
            /** Task Id */
            task_id?: string | null;
        };
        /** MultiAgentExecuteResponse */
        MultiAgentExecuteResponse: {
            /** Architecture */
            architecture: string;
            /** Final */
            final: string;
            /** Room Id */
            room_id: string;
            /**
             * Route Reason
             * @default
             */
            route_reason: string;
            /** Run Id */
            run_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "completed" | "failed";
            /** Task Id */
            task_id: string;
            /** Turns */
            turns: components["schemas"]["MultiAgentTurnResponse"][];
        };
        /** MultiAgentTurnResponse */
        MultiAgentTurnResponse: {
            /** Agent Id */
            agent_id: string;
            /** Content */
            content: string;
            /** Responsibility */
            responsibility: string;
            /** Sequence */
            sequence: number;
        };
        /** PersonaBindingResponse */
        PersonaBindingResponse: {
            /** Binding Id */
            binding_id: string;
            /** Capabilities */
            capabilities: string[];
            /** Persona Id */
            persona_id: string;
            /** Persona Version */
            persona_version: number;
            /** Role Id */
            role_id: string;
        };
        /** PersonaCreateRequest */
        PersonaCreateRequest: {
            /** Display Name */
            display_name: string;
            /** Persona Id */
            persona_id: string;
            /** Role Id */
            role_id: string;
            /** System Prompt */
            system_prompt: string;
            /**
             * Tone
             * @default professional
             */
            tone: string;
        };
        /** PersonaResponse */
        PersonaResponse: {
            /** Display Name */
            display_name: string;
            /** Persona Id */
            persona_id: string;
            /** Role Id */
            role_id: string;
            /** System Prompt */
            system_prompt: string;
            /** Tone */
            tone: string;
            /** Version */
            version: number;
        };
        /** PlanCompileRequest */
        PlanCompileRequest: {
            /**
             * Architecture
             * @default direct
             * @enum {string}
             */
            architecture: "direct" | "hierarchical" | "graph";
            /**
             * Budget Units
             * @default 100
             */
            budget_units: number;
            /** Goal */
            goal: string;
            /**
             * Max Agents
             * @default 1
             */
            max_agents: number;
            /**
             * Mode
             * @default auto
             * @enum {string}
             */
            mode: "auto" | "direct" | "delegate";
            /** Required Capabilities */
            required_capabilities?: string[];
            /**
             * Requires Decomposition
             * @default false
             */
            requires_decomposition: boolean;
            /** Task Id */
            task_id: string;
        };
        /** PlanCompileResponse */
        PlanCompileResponse: {
            /** Architecture */
            architecture: string;
            /** Budget Units */
            budget_units: number;
            /** Members */
            members: string[];
            /**
             * Mode
             * @enum {string}
             */
            mode: "direct" | "delegate";
            /** Plan Id */
            plan_id: string;
            /** Steps */
            steps: string[];
            /** Task Id */
            task_id: string;
        };
        /** RoleListResponse */
        RoleListResponse: {
            /** Items */
            items: components["schemas"]["RoleResponse"][];
        };
        /** RoleResponse */
        RoleResponse: {
            /** Capabilities */
            capabilities: string[];
            /** Department */
            department: string;
            /** Name */
            name: string;
            /** Responsibilities */
            responsibilities: string[];
            /** Role Id */
            role_id: string;
        };
        /** RoomCreateRequest */
        RoomCreateRequest: {
            /** Room Id */
            room_id?: string | null;
            /** Space Id */
            space_id: string;
            /**
             * Title
             * @default
             */
            title: string;
        };
        /** RoomListResponse */
        RoomListResponse: {
            /** Items */
            items: components["schemas"]["RoomResponse"][];
        };
        /** RoomResponse */
        RoomResponse: {
            /** Room Id */
            room_id: string;
            /** Room Sequence */
            room_sequence: number;
            /** Row Version */
            row_version: number;
            /** Space Id */
            space_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "archived" | "deleted";
            /** Title */
            title: string;
        };
        /** RunCreateRequest */
        RunCreateRequest: {
            /**
             * Plan Revision
             * @default 1
             */
            plan_revision: number;
            /** Run Id */
            run_id?: string | null;
            /**
             * Status
             * @default queued
             * @enum {string}
             */
            status: "queued" | "running";
            /** Task Id */
            task_id?: string | null;
        };
        /** RunResponse */
        RunResponse: {
            /** Control Epoch */
            control_epoch: number;
            /** Plan Revision */
            plan_revision: number;
            /** Row Version */
            row_version: number;
            /** Run Id */
            run_id: string;
            /** Status */
            status: string;
        };
        /** TaskCreateRequest */
        TaskCreateRequest: {
            /** Room Id */
            room_id: string;
            /** Task Id */
            task_id?: string | null;
            /** Title */
            title: string;
        };
        /** TaskResponse */
        TaskResponse: {
            /** Active Run Id */
            active_run_id: string | null;
            /** Room Id */
            room_id: string;
            /** Status */
            status: string;
            /** Task Id */
            task_id: string;
            /** Title */
            title: string;
            /** Version */
            version: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_artifact_artifacts__artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_asset_assets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssetUploadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_asset_assets__asset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assistant_message_assistant_messages_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssistantMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantMessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_command_commands__command_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                command_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommandRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    bind_persona_persona_bindings_post: {
        parameters: {
            query: {
                persona_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaBindingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_persona_persona_profiles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonaCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_persona_persona_profiles__persona_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                persona_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compile_plan_plans_compile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanCompileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanCompileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_roles_roles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleListResponse"];
                };
            };
        };
    };
    list_rooms_rooms_get: {
        parameters: {
            query?: {
                space_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_room_rooms_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_room_rooms__room_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_rooms__room_id__events_get: {
        parameters: {
            query?: {
                after?: number;
                limit?: number;
            };
            header?: never;
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_rooms__room_id__events_stream_get: {
        parameters: {
            query?: {
                after?: number;
                follow?: boolean;
                timeout?: number;
            };
            header?: never;
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_rooms__room_id__events__event_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: string;
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_rooms__room_id__members_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_messages_rooms__room_id__messages_get: {
        parameters: {
            query?: {
                after?: number;
                limit?: number;
            };
            header?: never;
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_message_rooms__room_id__messages_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_multi_agent_rooms__room_id__multi_agent_execute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MultiAgentExecuteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MultiAgentExecuteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    model_settings_settings_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelSettingsResponse"];
                };
            };
        };
    };
    update_model_setting_settings_models__agent_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelBindingUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelSettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_followup_tasks__task_id__followups_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FollowupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_message_tasks__task_id__messages_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FollowupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
