import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { api } from "../shared/api/client";

export function CompanyPage() {
  const roles = useQuery({ queryKey: ["roles"], queryFn: api.roles });
  const queryClient = useQueryClient();
  const settings = useQuery({ queryKey: ["model-settings"], queryFn: api.modelSettings });
  const [tiers, setTiers] = useState<Record<string, string>>({});
  const update = useMutation({ mutationFn: ({ agentId, sourceAgentId, tier }: { agentId: string; sourceAgentId: string; tier?: string }) => api.updateModelBinding(agentId, sourceAgentId, tier), onSuccess: (data) => queryClient.setQueryData(["model-settings"], data) });
  return <section className="page"><header className="page-header"><div><p className="eyebrow">公司设置</p><h1>角色与人设</h1><p className="subtitle">角色定义职责和能力，人设只影响表达；模型调整只作用于新任务，运行中的任务保留模型快照。</p></div></header><div className="role-grid">{roles.isLoading && <p className="muted">加载角色…</p>}{roles.isError && <p className="error-text">角色读取失败</p>}{roles.data?.items.map((role) => <article className="panel role-card" key={role.role_id}><p className="eyebrow">{role.department}</p><h2>{role.name}</h2><p className="muted">职责：{role.responsibilities.join("、")}</p><p className="muted">能力：{role.capabilities.join(" · ")}</p></article>)}</div><article className="panel model-settings"><div className="panel-heading"><div><p className="eyebrow">Runtime 设置</p><h2>Agent 模型绑定</h2></div></div>{settings.isLoading && <p className="muted">加载模型目录…</p>}{settings.isError && <p className="error-text">模型配置不可用，请检查本地 JSON 和 API Key</p>}{settings.data?.agents.map((agent) => <div className="model-row" key={agent.agent_id}><div><b>{agent.display_name}</b><p className="muted">{agent.agent_id} · {agent.tier} · {agent.model}</p><small className="muted">模态：{agent.modalities.join("、")}</small></div><select value={agent.agent_id} onChange={(event) => update.mutate({ agentId: agent.agent_id, sourceAgentId: event.target.value, tier: tiers[agent.agent_id] })} disabled={update.isPending}><option value={agent.agent_id}>保持当前模型</option>{settings.data.models.filter((model) => model.source_agent_id !== agent.agent_id).map((model) => <option key={`${agent.agent_id}-${model.source_agent_id}`} value={model.source_agent_id}>{model.provider} / {model.model}</option>)}</select><input aria-label={`${agent.display_name}等级`} value={tiers[agent.agent_id] ?? agent.tier} onChange={(event) => setTiers((current) => ({ ...current, [agent.agent_id]: event.target.value }))} placeholder="等级，例如 strong" /></div>)}</article></section>;
}
